In [15]:
import numpy as np
a=np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [55]:
b=np.array([[[1,2,4],[10,12,14]],[[7,5,8],[11,13,15]],[[1,6,9],[16,17,19]]])
b
sum=0
for i in b:
    print(i)
    for j in i:
        print(j)
        for k in j:
            print(k)
            sum=sum+int(k)
print(sum)

[[ 1  2  4]
 [10 12 14]]
[1 2 4]
1
2
4
[10 12 14]
10
12
14
[[ 7  5  8]
 [11 13 15]]
[7 5 8]
7
5
8
[11 13 15]
11
13
15
[[ 1  6  9]
 [16 17 19]]
[1 6 9]
1
6
9
[16 17 19]
16
17
19
170


In [56]:
b.ndim

3

In [57]:
b.shape

(3, 2, 3)

In [58]:
b.size

18

In [78]:
c=np.array([[[12324,"anbu"]],[["carl","doll"]]],)
c.dtype

dtype('<U11')

In [83]:
c[1][0]

array(['carl', 'doll'], dtype='<U11')